name = "sentinel-api"
main = "src/api/worker.ts"
compatibility_date = "2026-02-10"
compatibility_flags = [ "nodejs_compat" ]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "c6dec00f6b494b4592c14151d3526636"
localConnectionString = "postgres://oximy:oximy@localhost:5433/oximy"
